#:kivy 1.0.9

<KurveGame>:
    size:(1280,736)
    pos:(0,0)
    snake1:snake1
    snake2:snake2
    
    Snake:
        id:snake1
        canvas:
            Color:
                rgb: (255,255,0)
            
    Snake:
        id:snake2
        canvas:
            Color:
                rgb: (0,191,255)
        
<Snake>:
    size:10,10
    canvas:
        Ellipse:
            size:self.size 
            pos:self.pos   
